name: KBFFA
version: "2.0"
api-version: "1.14"
author: realmayus
main: me.mayus.KnockbackFFA.Main
depend:
    - Multiverse-Core
commands:
    kbffa:
        description: All commands for KBFFA.
        usage: /kbffa <setup[2-4]|lobby|leave>
    build:
        description: Buildmode in the Lobby!
    kit:
        description: Opens a GUI where you can buy or equip kits.
    kits:
        description: Opens a GUI where you can buy or equip kits.
